### PR TITLE
feat(FOROME-1620): add info panel in secondary datasets in wizard

### PR DESCRIPTION
**Pull request by QSdmitrioul**
[Task](https://quantori.atlassian.net/browse/FOROME-1620)

### CODE REVIEW

**Comment by AndreyUstyumenko** [comment]
Found a bug:
Click on an XL ds first
Then click on a root WS -> There is no info panel
Click on another WS -> info panel appears

**Comment by QSdmitrioul** [comment]
Fixed

**Review by Lapk1n — APPROVED** [review]

**Comment by AndreyUstyumenko** [comment]
Styles are gone for the code
Screen Shot 2022-09-08 at 16 14 51
Screen Shot 2022-09-08 at 16 15 07
Screen Shot 2022-09-08 at 16 15 17

**Comment by AndreyUstyumenko** [comment]
You can leave the classes that come in the response and copy styles for them from the Sergey's UI

**Review by AndreyUstyumenko — APPROVED** [review]

**Pull request merged**
