### PR TITLE
refactor(FOROME-1218): refactored main table

### PR DESCRIPTION
**Pull request by AlMaQntr**
- [x] need to add virtualized windowed view

### CODE REVIEW

**Review by QSdmitrioul — APPROVED** [review]

**Comment by Lapk1n** [comment]
Samples col lost its internal horizontal scroll:
1. Open xl_PF0005_wes/zurexa

**Review by EvgeniySobolev — APPROVED** [review]

**Comment by AlMaQntr** [comment]
> 1. 0005_wes/zurexa

Yes, i forgot it) thx

**Comment by AlMaQntr** [comment]
> > 1. 0005_wes/zurexa
> 
> Yes, i forgot it) thx

added

**Review by AndreyUstyumenko — APPROVED** [review]

**Comment by AndreyUstyumenko** [comment]
Can you add an animation when drawer appears?

**Review by Lapk1n — APPROVED** [review]

**Pull request merged**
